### PR TITLE
Fixed blending with other apps

### LINKED ISSUE #102: Blending recursive looping
blending is getting into a recursive loop withing People app

### Steps to reproduce
1. Run following apps:
 . SignIn
 . People
 . Images
2. click on `Edit` for any existing person in People app.

### Expected result
only person partial handler should be invoked `("/people/partials/persons/{?}")`

### Actual result
organization handler is being invoked as well `("/people/partials/organizations/{?}")` causing odd behaviour

### PR DESCRIPTION
**Pull request by bouguila**
fix #102
fix StarcounterApps/People#95
fix StarcounterApps/People#97
fix StarcounterApps/People#98

### CODE REVIEW

File: src/Images/Api/MainHandlers.cs [hunk 1]
```diff
@@ -47,9 +47,9 @@ protected void RegisterMapping()
             Blender.MapUri("/images/app-name", "app-name");
             Blender.MapUri("/images/partials/settings", "settings");
 
-            Blender.MapUri<Person>("/images/partials/somethings-edit/{?}");
-            Blender.MapUri<Organization>("/images/partials/somethings-edit/{?}");
-            Blender.MapUri<Product>("/images/partials/somethings-edit/{?}");
+            Blender.MapUri<Person>("/images/partials/somethings-edit/{?}", x => null, x => x);
+            Blender.MapUri<Organization>("/images/partials/somethings-edit/{?}", x => null, x => x);
+            Blender.MapUri<Product>("/images/partials/somethings-edit/{?}", x => null, x => x);
```
Comment (warpech) [inline src/Images/Api/MainHandlers.cs]: This is a neat workaround! According to the page https://docs.starcounter.io/guides/blending/blending/, the following code should also work and be more performant:

```cs
Blender.MapUri<Person>("/images/partials/somethings-edit/{?}", null, x => x);
Blender.MapUri<Organization>("/images/partials/somethings-edit/{?}", null, x => x);
Blender.MapUri<Product>("/images/partials/somethings-edit/{?}", null, x => x);
```

Comment (bouguila) [inline src/Images/Api/MainHandlers.cs]: Perfect! Thanks
